// Full ISO-3166 country list with Ukrainian names. `code` is the ISO-3166-1
// alpha-2 code used to restrict geocoding (Nominatim `countrycodes`) and to
// derive the flag emoji at render time.

export interface Country {
  code: string; // ISO alpha-2, lowercase
  name: string; // Ukrainian name
}

// Flag emoji from a 2-letter country code via regional indicator symbols.
export function flagEmoji(code: string): string {
  if (!code || code.length !== 2) return "🏳️";
  const A = 0x1f1e6;
  const c = code.toUpperCase();
  return String.fromCodePoint(A + (c.charCodeAt(0) - 65), A + (c.charCodeAt(1) - 65));
}

// Sorted (UA alphabet) at module load so the dropdown is alphabetical.
export const COUNTRIES: Country[] = [
  { code: "au", name: "Австралія" },
  { code: "at", name: "Австрія" },
  { code: "az", name: "Азербайджан" },
  { code: "al", name: "Албанія" },
  { code: "dz", name: "Алжир" },
  { code: "ao", name: "Ангола" },
  { code: "ad", name: "Андорра" },
  { code: "ar", name: "Аргентина" },
  { code: "am", name: "Вірменія" },
  { code: "af", name: "Афганістан" },
  { code: "bs", name: "Багами" },
  { code: "bd", name: "Бангладеш" },
  { code: "bb", name: "Барбадос" },
  { code: "bh", name: "Бахрейн" },
  { code: "by", name: "Білорусь" },
  { code: "bz", name: "Беліз" },
  { code: "be", name: "Бельгія" },
  { code: "bj", name: "Бенін" },
  { code: "bg", name: "Болгарія" },
  { code: "bo", name: "Болівія" },
  { code: "ba", name: "Боснія і Герцеговина" },
  { code: "bw", name: "Ботсвана" },
  { code: "br", name: "Бразилія" },
  { code: "bn", name: "Бруней" },
  { code: "bf", name: "Буркіна-Фасо" },
  { code: "bi", name: "Бурунді" },
  { code: "bt", name: "Бутан" },
  { code: "vu", name: "Вануату" },
  { code: "va", name: "Ватикан" },
  { code: "gb", name: "Велика Британія" },
  { code: "ve", name: "Венесуела" },
  { code: "vn", name: "В'єтнам" },
  { code: "ga", name: "Габон" },
  { code: "ht", name: "Гаїті" },
  { code: "gy", name: "Гаяна" },
  { code: "gm", name: "Гамбія" },
  { code: "gh", name: "Гана" },
  { code: "gt", name: "Гватемала" },
  { code: "gn", name: "Гвінея" },
  { code: "gw", name: "Гвінея-Бісау" },
  { code: "hn", name: "Гондурас" },
  { code: "gd", name: "Гренада" },
  { code: "gr", name: "Греція" },
  { code: "ge", name: "Грузія" },
  { code: "dk", name: "Данія" },
  { code: "cd", name: "ДР Конго" },
  { code: "dj", name: "Джибуті" },
  { code: "dm", name: "Домініка" },
  { code: "do", name: "Домініканська Республіка" },
  { code: "eg", name: "Єгипет" },
  { code: "ec", name: "Еквадор" },
  { code: "gq", name: "Екваторіальна Гвінея" },
  { code: "er", name: "Еритрея" },
  { code: "ee", name: "Естонія" },
  { code: "sz", name: "Есватіні" },
  { code: "et", name: "Ефіопія" },
  { code: "ye", name: "Ємен" },
  { code: "zm", name: "Замбія" },
  { code: "zw", name: "Зімбабве" },
  { code: "il", name: "Ізраїль" },
  { code: "in", name: "Індія" },
  { code: "id", name: "Індонезія" },
  { code: "iq", name: "Ірак" },
  { code: "ir", name: "Іран" },
  { code: "ie", name: "Ірландія" },
  { code: "is", name: "Ісландія" },
  { code: "es", name: "Іспанія" },
  { code: "it", name: "Італія" },
  { code: "jo", name: "Йорданія" },
  { code: "cv", name: "Кабо-Верде" },
  { code: "kz", name: "Казахстан" },
  { code: "kh", name: "Камбоджа" },
  { code: "cm", name: "Камерун" },
  { code: "ca", name: "Канада" },
  { code: "qa", name: "Катар" },
  { code: "ke", name: "Кенія" },
  { code: "kg", name: "Киргизстан" },
  { code: "cn", name: "Китай" },
  { code: "cy", name: "Кіпр" },
  { code: "ki", name: "Кірибаті" },
  { code: "co", name: "Колумбія" },
  { code: "km", name: "Коморські Острови" },
  { code: "cg", name: "Конго" },
  { code: "cr", name: "Коста-Рика" },
  { code: "ci", name: "Кот-д'Івуар" },
  { code: "cu", name: "Куба" },
  { code: "kw", name: "Кувейт" },
  { code: "la", name: "Лаос" },
  { code: "lv", name: "Латвія" },
  { code: "ls", name: "Лесото" },
  { code: "lt", name: "Литва" },
  { code: "lr", name: "Ліберія" },
  { code: "lb", name: "Ліван" },
  { code: "ly", name: "Лівія" },
  { code: "li", name: "Ліхтенштейн" },
  { code: "lu", name: "Люксембург" },
  { code: "mu", name: "Маврикій" },
  { code: "mr", name: "Мавританія" },
  { code: "mg", name: "Мадагаскар" },
  { code: "mk", name: "Північна Македонія" },
  { code: "mw", name: "Малаві" },
  { code: "my", name: "Малайзія" },
  { code: "ml", name: "Малі" },
  { code: "mv", name: "Мальдіви" },
  { code: "mt", name: "Мальта" },
  { code: "ma", name: "Марокко" },
  { code: "mh", name: "Маршаллові Острови" },
  { code: "mx", name: "Мексика" },
  { code: "mz", name: "Мозамбік" },
  { code: "md", name: "Молдова" },
  { code: "mc", name: "Монако" },
  { code: "mn", name: "Монголія" },
  { code: "mm", name: "М'янма" },
  { code: "na", name: "Намібія" },
  { code: "nr", name: "Науру" },
  { code: "np", name: "Непал" },
  { code: "ne", name: "Нігер" },
  { code: "ng", name: "Нігерія" },
  { code: "nl", name: "Нідерланди" },
  { code: "ni", name: "Нікарагуа" },
  { code: "de", name: "Німеччина" },
  { code: "nz", name: "Нова Зеландія" },
  { code: "no", name: "Норвегія" },
  { code: "ae", name: "ОАЕ" },
  { code: "om", name: "Оман" },
  { code: "pk", name: "Пакистан" },
  { code: "pw", name: "Палау" },
  { code: "ps", name: "Палестина" },
  { code: "pa", name: "Панама" },
  { code: "pg", name: "Папуа Нова Гвінея" },
  { code: "py", name: "Парагвай" },
  { code: "pe", name: "Перу" },
  { code: "za", name: "ПАР" },
  { code: "pl", name: "Польща" },
  { code: "pt", name: "Португалія" },
  { code: "ru", name: "Росія" },
  { code: "rw", name: "Руанда" },
  { code: "ro", name: "Румунія" },
  { code: "sv", name: "Сальвадор" },
  { code: "ws", name: "Самоа" },
  { code: "sm", name: "Сан-Марино" },
  { code: "st", name: "Сан-Томе і Принсіпі" },
  { code: "sa", name: "Саудівська Аравія" },
  { code: "sc", name: "Сейшели" },
  { code: "sn", name: "Сенегал" },
  { code: "vc", name: "Сент-Вінсент і Гренадини" },
  { code: "kn", name: "Сент-Кітс і Невіс" },
  { code: "lc", name: "Сент-Люсія" },
  { code: "rs", name: "Сербія" },
  { code: "sg", name: "Сінгапур" },
  { code: "sy", name: "Сирія" },
  { code: "sk", name: "Словаччина" },
  { code: "si", name: "Словенія" },
  { code: "sb", name: "Соломонові Острови" },
  { code: "so", name: "Сомалі" },
  { code: "sd", name: "Судан" },
  { code: "ss", name: "Південний Судан" },
  { code: "sr", name: "Суринам" },
  { code: "tl", name: "Східний Тимор" },
  { code: "us", name: "США" },
  { code: "sl", name: "Сьєрра-Леоне" },
  { code: "tj", name: "Таджикистан" },
  { code: "th", name: "Таїланд" },
  { code: "tz", name: "Танзанія" },
  { code: "tg", name: "Того" },
  { code: "to", name: "Тонга" },
  { code: "tt", name: "Тринідад і Тобаго" },
  { code: "tv", name: "Тувалу" },
  { code: "tn", name: "Туніс" },
  { code: "tm", name: "Туркменістан" },
  { code: "tr", name: "Туреччина" },
  { code: "ug", name: "Уганда" },
  { code: "hu", name: "Угорщина" },
  { code: "uz", name: "Узбекистан" },
  { code: "ua", name: "Україна" },
  { code: "uy", name: "Уругвай" },
  { code: "fj", name: "Фіджі" },
  { code: "ph", name: "Філіппіни" },
  { code: "fi", name: "Фінляндія" },
  { code: "fr", name: "Франція" },
  { code: "hr", name: "Хорватія" },
  { code: "cf", name: "ЦАР" },
  { code: "td", name: "Чад" },
  { code: "me", name: "Чорногорія" },
  { code: "cz", name: "Чехія" },
  { code: "cl", name: "Чилі" },
  { code: "ch", name: "Швейцарія" },
  { code: "se", name: "Швеція" },
  { code: "lk", name: "Шрі-Ланка" },
  { code: "jm", name: "Ямайка" },
  { code: "jp", name: "Японія" },
].sort((a, b) => a.name.localeCompare(b.name, "uk"));
