// Full ISO-3166 country list with Ukrainian names. `code` is the ISO-3166-1
// alpha-2 code used to restrict geocoding (Nominatim `countrycodes`) and to
// derive the flag emoji at render time.

export interface Country {
  code: string; // ISO alpha-2, lowercase
  name: string; // Ukrainian name
}

// Flag emoji from a 2-letter country code via regional indicator symbols.
export function flagEmoji(code: string): string {
  if (!code || code.length !== 2) return "🏳️";
  const A = 0x1f1e6;
  const c = code.toUpperCase();
  return String.fromCodePoint(A + (c.charCodeAt(0) - 65), A + (c.charCodeAt(1) - 65));
}

// ── Top niches per country ──────────────────────────────────────────────
// When a country is picked, the search form offers these as one-click niche
// chips (no manual typing). Each token MUST be a key in osm-search KEYWORD_MAP
// so it resolves to real OSM tags and returns leads. Lists are curated per
// market: Gulf = real-estate/tourism heavy, US/UK/AU = trades & pro-services,
// Mediterranean = hospitality, etc. Unlisted countries fall back to DEFAULT.
export const DEFAULT_NICHES = [
  "restaurant", "cafe", "beauty", "dentist", "lawyer",
  "car_repair", "gym", "hotel", "real_estate", "pharmacy",
];

export const COUNTRY_NICHES: Record<string, string[]> = {
  // Gulf / MENA — luxury, real estate, tourism, personal services
  ae: ["real_estate", "restaurant", "beauty", "dentist", "car_repair", "hotel", "gym", "clinic", "lawyer", "travel"],
  sa: ["real_estate", "restaurant", "car_repair", "beauty", "dentist", "clinic", "gym", "hotel", "jewelry", "travel"],
  qa: ["real_estate", "restaurant", "hotel", "beauty", "dentist", "car_repair", "gym", "clinic", "travel", "lawyer"],
  kw: ["restaurant", "beauty", "real_estate", "car_repair", "dentist", "gym", "clinic", "hotel", "jewelry", "cafe"],
  bh: ["restaurant", "beauty", "real_estate", "dentist", "car_repair", "gym", "hotel", "clinic", "cafe", "lawyer"],
  om: ["hotel", "restaurant", "real_estate", "car_repair", "beauty", "dentist", "travel", "gym", "clinic", "cafe"],
  eg: ["restaurant", "hotel", "travel", "beauty", "car_repair", "dentist", "real_estate", "gym", "cafe", "lawyer"],
  tr: ["restaurant", "hotel", "beauty", "dentist", "car_repair", "real_estate", "gym", "cafe", "jewelry", "lawyer"],
  ma: ["restaurant", "hotel", "cafe", "beauty", "car_repair", "real_estate", "dentist", "travel", "gym", "jewelry"],

  // North America — trades & professional services
  us: ["dentist", "lawyer", "plumber", "restaurant", "gym", "beauty", "car_repair", "real_estate", "accountant", "veterinary"],
  ca: ["dentist", "restaurant", "plumber", "lawyer", "gym", "beauty", "car_repair", "real_estate", "accountant", "veterinary"],
  mx: ["restaurant", "beauty", "dentist", "car_repair", "hotel", "real_estate", "gym", "lawyer", "cafe", "pharmacy"],

  // Western Europe
  gb: ["restaurant", "cafe", "dentist", "plumber", "beauty", "lawyer", "gym", "car_repair", "real_estate", "electrician"],
  ie: ["restaurant", "cafe", "dentist", "plumber", "beauty", "lawyer", "gym", "car_repair", "real_estate", "electrician"],
  de: ["restaurant", "bakery", "dentist", "lawyer", "car_repair", "beauty", "plumber", "real_estate", "gym", "accountant"],
  fr: ["restaurant", "cafe", "bakery", "beauty", "dentist", "lawyer", "real_estate", "hotel", "gym", "car_repair"],
  es: ["restaurant", "cafe", "hotel", "beauty", "dentist", "lawyer", "real_estate", "bakery", "gym", "car_repair"],
  it: ["restaurant", "cafe", "hotel", "beauty", "dentist", "bakery", "lawyer", "real_estate", "gym", "car_repair"],
  pt: ["restaurant", "cafe", "hotel", "beauty", "dentist", "real_estate", "lawyer", "bakery", "gym", "car_repair"],
  nl: ["cafe", "restaurant", "dentist", "beauty", "lawyer", "real_estate", "gym", "bakery", "car_repair", "accountant"],
  be: ["restaurant", "cafe", "bakery", "dentist", "beauty", "lawyer", "real_estate", "gym", "car_repair", "accountant"],
  ch: ["restaurant", "dentist", "lawyer", "beauty", "real_estate", "gym", "car_repair", "accountant", "hotel", "architect"],
  at: ["restaurant", "cafe", "bakery", "dentist", "beauty", "lawyer", "hotel", "gym", "car_repair", "real_estate"],

  // Nordics
  se: ["restaurant", "cafe", "dentist", "beauty", "gym", "car_repair", "real_estate", "lawyer", "hairdresser", "accountant"],
  no: ["restaurant", "cafe", "dentist", "beauty", "gym", "car_repair", "real_estate", "hairdresser", "lawyer", "plumber"],
  dk: ["restaurant", "cafe", "dentist", "beauty", "gym", "car_repair", "real_estate", "hairdresser", "bakery", "lawyer"],
  fi: ["restaurant", "cafe", "dentist", "beauty", "gym", "car_repair", "real_estate", "hairdresser", "lawyer", "hotel"],

  // Central & Eastern Europe
  pl: ["restaurant", "beauty", "dentist", "lawyer", "car_repair", "gym", "bakery", "real_estate", "plumber", "pharmacy"],
  cz: ["restaurant", "cafe", "beauty", "dentist", "car_repair", "gym", "real_estate", "lawyer", "hotel", "pharmacy"],
  ua: ["кафе", "ресторан", "салон", "стоматолог", "сто", "юрист", "готель", "спортзал", "пекарня", "аптека"],
  ro: ["restaurant", "beauty", "dentist", "car_repair", "gym", "real_estate", "lawyer", "cafe", "hotel", "pharmacy"],
  gr: ["restaurant", "cafe", "hotel", "beauty", "dentist", "car_repair", "real_estate", "gym", "travel", "lawyer"],
  hr: ["restaurant", "cafe", "hotel", "beauty", "dentist", "car_repair", "real_estate", "travel", "gym", "bakery"],

  // Asia-Pacific
  au: ["restaurant", "cafe", "dentist", "plumber", "beauty", "gym", "car_repair", "real_estate", "lawyer", "electrician"],
  nz: ["restaurant", "cafe", "dentist", "plumber", "beauty", "gym", "car_repair", "real_estate", "lawyer", "hotel"],
  sg: ["restaurant", "beauty", "dentist", "gym", "real_estate", "car_repair", "cafe", "lawyer", "clinic", "hotel"],
  in: ["restaurant", "beauty", "dentist", "gym", "real_estate", "car_repair", "hotel", "jewelry", "clinic", "lawyer"],
  jp: ["restaurant", "cafe", "beauty", "dentist", "hairdresser", "gym", "hotel", "car_repair", "real_estate", "bakery"],
  th: ["restaurant", "hotel", "beauty", "massage", "cafe", "car_repair", "real_estate", "dentist", "gym", "travel"],
  my: ["restaurant", "cafe", "beauty", "dentist", "car_repair", "real_estate", "gym", "hotel", "clinic", "travel"],
  id: ["restaurant", "cafe", "beauty", "hotel", "car_repair", "real_estate", "dentist", "gym", "travel", "clinic"],
  ph: ["restaurant", "cafe", "beauty", "dentist", "car_repair", "real_estate", "gym", "hotel", "clinic", "travel"],

  // Latin America
  br: ["restaurant", "beauty", "dentist", "car_repair", "gym", "real_estate", "cafe", "lawyer", "hotel", "pharmacy"],
  ar: ["restaurant", "cafe", "beauty", "dentist", "car_repair", "gym", "real_estate", "lawyer", "hotel", "bakery"],

  // Africa
  za: ["restaurant", "cafe", "dentist", "beauty", "car_repair", "gym", "real_estate", "lawyer", "hotel", "plumber"],
  ng: ["restaurant", "beauty", "hotel", "car_repair", "real_estate", "dentist", "gym", "lawyer", "cafe", "travel"],
};

// Top niches for a country code, falling back to a sensible default list.
export function nichesForCountry(code: string): string[] {
  return COUNTRY_NICHES[code?.toLowerCase()] ?? DEFAULT_NICHES;
}

// Sorted (UA alphabet) at module load so the dropdown is alphabetical.
export const COUNTRIES: Country[] = [
  { code: "au", name: "Австралія" },
  { code: "at", name: "Австрія" },
  { code: "az", name: "Азербайджан" },
  { code: "al", name: "Албанія" },
  { code: "dz", name: "Алжир" },
  { code: "ao", name: "Ангола" },
  { code: "ad", name: "Андорра" },
  { code: "ar", name: "Аргентина" },
  { code: "am", name: "Вірменія" },
  { code: "af", name: "Афганістан" },
  { code: "bs", name: "Багами" },
  { code: "bd", name: "Бангладеш" },
  { code: "bb", name: "Барбадос" },
  { code: "bh", name: "Бахрейн" },
  { code: "by", name: "Білорусь" },
  { code: "bz", name: "Беліз" },
  { code: "be", name: "Бельгія" },
  { code: "bj", name: "Бенін" },
  { code: "bg", name: "Болгарія" },
  { code: "bo", name: "Болівія" },
  { code: "ba", name: "Боснія і Герцеговина" },
  { code: "bw", name: "Ботсвана" },
  { code: "br", name: "Бразилія" },
  { code: "bn", name: "Бруней" },
  { code: "bf", name: "Буркіна-Фасо" },
  { code: "bi", name: "Бурунді" },
  { code: "bt", name: "Бутан" },
  { code: "vu", name: "Вануату" },
  { code: "va", name: "Ватикан" },
  { code: "gb", name: "Велика Британія" },
  { code: "ve", name: "Венесуела" },
  { code: "vn", name: "В'єтнам" },
  { code: "ga", name: "Габон" },
  { code: "ht", name: "Гаїті" },
  { code: "gy", name: "Гаяна" },
  { code: "gm", name: "Гамбія" },
  { code: "gh", name: "Гана" },
  { code: "gt", name: "Гватемала" },
  { code: "gn", name: "Гвінея" },
  { code: "gw", name: "Гвінея-Бісау" },
  { code: "hn", name: "Гондурас" },
  { code: "gd", name: "Гренада" },
  { code: "gr", name: "Греція" },
  { code: "ge", name: "Грузія" },
  { code: "dk", name: "Данія" },
  { code: "cd", name: "ДР Конго" },
  { code: "dj", name: "Джибуті" },
  { code: "dm", name: "Домініка" },
  { code: "do", name: "Домініканська Республіка" },
  { code: "eg", name: "Єгипет" },
  { code: "ec", name: "Еквадор" },
  { code: "gq", name: "Екваторіальна Гвінея" },
  { code: "er", name: "Еритрея" },
  { code: "ee", name: "Естонія" },
  { code: "sz", name: "Есватіні" },
  { code: "et", name: "Ефіопія" },
  { code: "ye", name: "Ємен" },
  { code: "zm", name: "Замбія" },
  { code: "zw", name: "Зімбабве" },
  { code: "il", name: "Ізраїль" },
  { code: "in", name: "Індія" },
  { code: "id", name: "Індонезія" },
  { code: "iq", name: "Ірак" },
  { code: "ir", name: "Іран" },
  { code: "ie", name: "Ірландія" },
  { code: "is", name: "Ісландія" },
  { code: "es", name: "Іспанія" },
  { code: "it", name: "Італія" },
  { code: "jo", name: "Йорданія" },
  { code: "cv", name: "Кабо-Верде" },
  { code: "kz", name: "Казахстан" },
  { code: "kh", name: "Камбоджа" },
  { code: "cm", name: "Камерун" },
  { code: "ca", name: "Канада" },
  { code: "qa", name: "Катар" },
  { code: "ke", name: "Кенія" },
  { code: "kg", name: "Киргизстан" },
  { code: "cn", name: "Китай" },
  { code: "cy", name: "Кіпр" },
  { code: "ki", name: "Кірибаті" },
  { code: "co", name: "Колумбія" },
  { code: "km", name: "Коморські Острови" },
  { code: "cg", name: "Конго" },
  { code: "cr", name: "Коста-Рика" },
  { code: "ci", name: "Кот-д'Івуар" },
  { code: "cu", name: "Куба" },
  { code: "kw", name: "Кувейт" },
  { code: "la", name: "Лаос" },
  { code: "lv", name: "Латвія" },
  { code: "ls", name: "Лесото" },
  { code: "lt", name: "Литва" },
  { code: "lr", name: "Ліберія" },
  { code: "lb", name: "Ліван" },
  { code: "ly", name: "Лівія" },
  { code: "li", name: "Ліхтенштейн" },
  { code: "lu", name: "Люксембург" },
  { code: "mu", name: "Маврикій" },
  { code: "mr", name: "Мавританія" },
  { code: "mg", name: "Мадагаскар" },
  { code: "mk", name: "Північна Македонія" },
  { code: "mw", name: "Малаві" },
  { code: "my", name: "Малайзія" },
  { code: "ml", name: "Малі" },
  { code: "mv", name: "Мальдіви" },
  { code: "mt", name: "Мальта" },
  { code: "ma", name: "Марокко" },
  { code: "mh", name: "Маршаллові Острови" },
  { code: "mx", name: "Мексика" },
  { code: "mz", name: "Мозамбік" },
  { code: "md", name: "Молдова" },
  { code: "mc", name: "Монако" },
  { code: "mn", name: "Монголія" },
  { code: "mm", name: "М'янма" },
  { code: "na", name: "Намібія" },
  { code: "nr", name: "Науру" },
  { code: "np", name: "Непал" },
  { code: "ne", name: "Нігер" },
  { code: "ng", name: "Нігерія" },
  { code: "nl", name: "Нідерланди" },
  { code: "ni", name: "Нікарагуа" },
  { code: "de", name: "Німеччина" },
  { code: "nz", name: "Нова Зеландія" },
  { code: "no", name: "Норвегія" },
  { code: "ae", name: "ОАЕ" },
  { code: "om", name: "Оман" },
  { code: "pk", name: "Пакистан" },
  { code: "pw", name: "Палау" },
  { code: "ps", name: "Палестина" },
  { code: "pa", name: "Панама" },
  { code: "pg", name: "Папуа Нова Гвінея" },
  { code: "py", name: "Парагвай" },
  { code: "pe", name: "Перу" },
  { code: "za", name: "ПАР" },
  { code: "pl", name: "Польща" },
  { code: "pt", name: "Португалія" },
  { code: "ru", name: "Росія" },
  { code: "rw", name: "Руанда" },
  { code: "ro", name: "Румунія" },
  { code: "sv", name: "Сальвадор" },
  { code: "ws", name: "Самоа" },
  { code: "sm", name: "Сан-Марино" },
  { code: "st", name: "Сан-Томе і Принсіпі" },
  { code: "sa", name: "Саудівська Аравія" },
  { code: "sc", name: "Сейшели" },
  { code: "sn", name: "Сенегал" },
  { code: "vc", name: "Сент-Вінсент і Гренадини" },
  { code: "kn", name: "Сент-Кітс і Невіс" },
  { code: "lc", name: "Сент-Люсія" },
  { code: "rs", name: "Сербія" },
  { code: "sg", name: "Сінгапур" },
  { code: "sy", name: "Сирія" },
  { code: "sk", name: "Словаччина" },
  { code: "si", name: "Словенія" },
  { code: "sb", name: "Соломонові Острови" },
  { code: "so", name: "Сомалі" },
  { code: "sd", name: "Судан" },
  { code: "ss", name: "Південний Судан" },
  { code: "sr", name: "Суринам" },
  { code: "tl", name: "Східний Тимор" },
  { code: "us", name: "США" },
  { code: "sl", name: "Сьєрра-Леоне" },
  { code: "tj", name: "Таджикистан" },
  { code: "th", name: "Таїланд" },
  { code: "tz", name: "Танзанія" },
  { code: "tg", name: "Того" },
  { code: "to", name: "Тонга" },
  { code: "tt", name: "Тринідад і Тобаго" },
  { code: "tv", name: "Тувалу" },
  { code: "tn", name: "Туніс" },
  { code: "tm", name: "Туркменістан" },
  { code: "tr", name: "Туреччина" },
  { code: "ug", name: "Уганда" },
  { code: "hu", name: "Угорщина" },
  { code: "uz", name: "Узбекистан" },
  { code: "ua", name: "Україна" },
  { code: "uy", name: "Уругвай" },
  { code: "fj", name: "Фіджі" },
  { code: "ph", name: "Філіппіни" },
  { code: "fi", name: "Фінляндія" },
  { code: "fr", name: "Франція" },
  { code: "hr", name: "Хорватія" },
  { code: "cf", name: "ЦАР" },
  { code: "td", name: "Чад" },
  { code: "me", name: "Чорногорія" },
  { code: "cz", name: "Чехія" },
  { code: "cl", name: "Чилі" },
  { code: "ch", name: "Швейцарія" },
  { code: "se", name: "Швеція" },
  { code: "lk", name: "Шрі-Ланка" },
  { code: "jm", name: "Ямайка" },
  { code: "jp", name: "Японія" },
].sort((a, b) => a.name.localeCompare(b.name, "uk"));
